services:
  # ----------------
  # Reverse Proxy
  # ----------------
  traefik:
    image: traefik:v3.2
    command:
      - "--log.level=INFO"  # Changed from DEBUG for production
      - "--accesslog=true"
      - "--accesslog.fields.headers.names.User-Agent=keep"
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Consider setting to false in production
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"
      - "--certificatesresolvers.myresolver.acme.email=info@deep-research.eu"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Consider restricting access to dashboard in production
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Added read-only for security
    networks:
      - traefik
    restart: unless-stopped

  # ----------------
  # Frontend (Next.js)
  # ----------------
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        NEXT_PUBLIC_API_URL: https://smartmarks.deep-research.eu/api
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.frontend.rule=Host(`smartmarks.deep-research.eu`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
    # Removed ports section - not needed with Traefik
    # Removed environment section - handled by build args

  # ----------------
  # Backend (Flask)
  # ----------------
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    restart: unless-stopped
    user: "0:0"
    volumes:
      - ./documents:/app/documents  # Fixed path
      - ./uploads:/app/uploads      # Fixed path
      - ./generated_pdfs:/app/generated_pdfs  # Added missing volume
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.backend.rule=Host(`smartmarks.deep-research.eu`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.routers.backend.priority=10"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"  # Added missing middleware
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"           # Added missing middleware
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}

networks:
  traefik:
    name: traefik
    driver: bridge
    external: false

volumes:
  letsencrypt: